### ISSUE TITLE
EditorService could not start properly?

### ISSUE THREAD

**Issue by mslu1982** [PowerShell/PowerShellEditorServices#1105]
Hi 

i am now configuring powershell with VScode , the autocompletion is not working, i enabled diagnostic log,  below is some error of editor service, please help to check.

    PowerShell Editor Services Host v1.13.1.0 starting (PID 18523

      Host application details:

        Name:      Visual Studio Code Host
        Version:   2019.11.0
        ProfileId: Microsoft.VSCode
        Arch:      X64

      Operating system details:

        Version: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
        Arch:    X64

      Build information:

        Version:
        Origin:  VSTS
        Date:    2019-11-02T20:52:22

2019-11-18 17:29:13.943 [NORMAL] tid:13 in 'StartLanguageService' D:\a\1\s\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 202
    Language service started, type = NamedPipe, endpoint =  InOut pipe: PSES_50pnez4g.l05

2019-11-18 17:29:13.949 [NORMAL] tid:13 in 'StartDebugService' D:\a\1\s\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 279
    Debug service started, type = NamedPipe, endpoint =  InOut pipe: PSES_g4mxyosy.rr4

2019-11-18 17:29:14.453 [ERROR] tid:4 in 'ListenForConnection' D:\a\1\s\src\PowerShellEditorServices.Protocol\MessageProtocol\Channel\NamedPipeServerListener.cs: line 155
    Exception: An unhandled exception occurred while listening for a named pipe client connection

    System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

    File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer, ILogger logger)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerChannel.Initialize(IMessageSerializer messageSerializer)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.ServerListenerBase`1.OnClientConnect(TChannel channel)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.<<ListenForConnection>b__9_0>d.MoveNext()

**Comment by TylerLeonhardt** [comment]
Can you give this a go in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? It has a ton of fixes in it and it might be fixed in that already.

**Comment by mslu1982** [comment]
This issue was fixed after i upgrade my powershell core version from 6.0.2 to 6.2.3 on my mac, and I did nothing on powershell plugin.
