### ISSUE TITLE
Sending processId as null in initialize method cause PowerShellEditorServices crash

### ISSUE THREAD

**Issue by kiennq** [PowerShell/PowerShellEditorServices#1194]
According to the [specs](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize), we can send `null` as value of `processId` in `InitializeParams`.
However, when I send `null` as `processId`, the language server is crashed.
Should we fix that?

**Comment by rjmholt** [comment]
Hi @kiennq, what version of PSES are you running? Can you link the stack trace of the crash you're seeing?

**Comment by TylerLeonhardt** [comment]
Looks like stable versions of PSES don't have a nullable int here:
https://github.com/PowerShell/PowerShellEditorServices/blob/3ba96daec6f4bee7fafc97c6363166b0f8d24434/src/PowerShellEditorServices.Protocol/LanguageServer/Initialize.cs#L27

But for preview versions of PSES which use [Omnisharp's lib](https://github.com/OmniSharp/csharp-language-server-protocol), they use a nullable long:
https://github.com/OmniSharp/csharp-language-server-protocol/blob/ad24c919109c16020c6641cd94989d5fccfbc73f/src/Protocol/Models/InitializeParams.cs#L18

We don't do anything with the ProcessId... so this should be fixed in the Preview versions.

**Comment by kiennq** [comment]
I'm using the latest release one [1.13.3](https://github.com/PowerShell/PowerShellEditorServices/releases/tag/v1.13.3).
And here is the stack traces
```
2020-02-15 03:26:48.849 [NORMAL] tid:8 in 'Initialize' D:\a\1\s\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 221
    PowerShell runtime version: 7.0.0, edition: Core

2020-02-15 03:26:49.244 [NORMAL] tid:8 in 'StartLanguageService' D:\a\1\s\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 202
    Language service started, type = Stdio, endpoint =  InOut pipe: 

2020-02-15 03:26:49.514 [ERROR] tid:6 in 'OnListenTaskCompleted' D:\a\1\s\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: line 391
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Error converting value {null} to type 'System.Int32'. Path 'params.processId', line 1, position 65.)
     ---> Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'params.processId', line 1, position 65.
     ---> System.InvalidCastException: Null object cannot be converted to a value type.
       at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
       --- End of inner exception stack trace ---
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
       at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
       at Newtonsoft.Json.Linq.JToken.ToObject[T]()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass4_0`4.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0()
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
       --- End of inner exception stack trace ---

2020-02-15 03:26:49.515 [ERROR] tid:6 in 'ProtocolEndpoint_UnhandledException' D:\a\1\s\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 448
    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.

2020-02-15 03:26:49.532 [ERROR] tid:1 in 'PopRunspace' D:\a\1\s\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 2109
    Caller attempted to pop a runspace when no runspaces are on the stack.

2020-02-15 03:26:49.532 [ERROR] tid:1 in 'PopRunspace' D:\a\1\s\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 2109
    Caller attempted to pop a runspace when no runspaces are on the stack.
```

**Comment by TylerLeonhardt** [comment]
Just as I suspected. We'll be moving the 2.0.0-preview version to stable this month and you should be unblocked then. You can give the preview version a go if you'd like which should work for you!

**Comment by kiennq** [comment]
Thanks, looking forward for new version :)
