### ISSUE TITLE
`NullReferenceException` in `GetDiagnosticFromMarker`

### ISSUE THREAD

**Issue by dkattan** [PowerShell/PowerShellEditorServices#1906]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I am experiencing an intermittent NullReferenceException in AnalysisService.cs https://github.com/PowerShell/PowerShellEditorServices/blob/ba293c9ce19857555b376a7fd47236a000ff67d6/src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs#L423

I don't know how to reproduce it, but it appears to be simple to fix.

### Expected behavior

```console
NullReferenceException should not happen
```

### Actual behavior

```console
NullReferenceException happens
```

### Error details

```console
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.PowerShell.EditorServices
  StackTrace:
   at Microsoft.PowerShell.EditorServices.Services.AnalysisService.GetDiagnosticFromMarker(ScriptFileMarker scriptFileMarker) in C:\Users\DKattan.IN\source\repos\PowerShellEditorServices\src\PowerShellEditorServices\Services\Analysis\AnalysisService.cs:line 421
   at Microsoft.PowerShell.EditorServices.Services.AnalysisService.PublishScriptDiagnostics(ScriptFile scriptFile, IReadOnlyList`1 markers) in C:\Users\DKattan.IN\source\repos\PowerShellEditorServices\src\PowerShellEditorServices\Services\Analysis\AnalysisService.cs:line 401
   at Microsoft.PowerShell.EditorServices.Services.AnalysisService.PublishScriptDiagnostics(ScriptFile scriptFile) in C:\Users\DKattan.IN\source\repos\PowerShellEditorServices\src\PowerShellEditorServices\Services\Analysis\AnalysisService.cs:line 385
   at Microsoft.PowerShell.EditorServices.Services.AnalysisService.<DelayThenInvokeDiagnosticsAsync>d__28.MoveNext() in C:\Users\DKattan.IN\source\repos\PowerShellEditorServices\src\PowerShellEditorServices\Services\Analysis\AnalysisService.cs:line 381
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.PowerShell.EditorServices.Services.AnalysisService.<GetMostRecentCodeActionsForFileAsync>d__19.MoveNext() in C:\Users\DKattan.IN\source\repos\PowerShellEditorServices\src\PowerShellEditorServices\Services\Analysis\AnalysisService.cs:line 228

  This exception was originally thrown at this call stack:
    Microsoft.PowerShell.EditorServices.Services.AnalysisService.GetDiagnosticFromMarker(Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFileMarker) in AnalysisService.cs
    Microsoft.PowerShell.EditorServices.Services.AnalysisService.PublishScriptDiagnostics(Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFile, System.Collections.Generic.IReadOnlyList<Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFileMarker>) in AnalysisService.cs
    Microsoft.PowerShell.EditorServices.Services.AnalysisService.PublishScriptDiagnostics(Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFile) in AnalysisService.cs
    Microsoft.PowerShell.EditorServices.Services.AnalysisService.DelayThenInvokeDiagnosticsAsync(Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFile[], System.Threading.CancellationToken) in AnalysisService.cs
    [External Code]
    Microsoft.PowerShell.EditorServices.Services.AnalysisService.GetMostRecentCodeActionsForFileAsync(OmniSharp.Extensions.LanguageServer.Protocol.DocumentUri) in AnalysisService.cs
```

### Environment data

```PowerShell
PowerShell 7.1.3 PSES 3.5.0
```

### Version

3.5.0

### Visuals

![image](https://user-images.githubusercontent.com/1424395/186319454-2877f4c9-39e1-41ed-9ed4-bbf304234af6.png)

![image](https://user-images.githubusercontent.com/1424395/186319753-53e51288-baa4-4c28-bf4a-9c613058592d.png)

![image](https://user-images.githubusercontent.com/1424395/186322177-4cab885e-2cac-4494-8ded-78123e79cfff.png)

**Comment by andschwa** [comment]
Ah, good find @dkattan. Don't have to time to get this into the next release, but triaged!
