### ISSUE TITLE
CodeLens related commands cause exception to be thrown

### ISSUE THREAD

**Issue by mhintzke** [PowerShell/PowerShellEditorServices#2172]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/PowerShellEditorServices/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with _PowerShell Editor Services itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance, and is not an issue with my editor.
- [X] I have verified that I am using the latest version of PowerShell Editor Services.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

In the repository below, I have forked @TylerLeonhardt's old Monaco + PSES example, upgraded to the (almost) latest version of all packages, and wrote up how to reproduce the issue in the `README.md`.

https://github.com/mhintzke/monaco-powershell

Basically, regardless of OS (Windows or Unix) when the editor detects that the contents contains a basic function, e.g. 

```pwsh
function Verb-Noun {

}
```

Then Monaco Client sends some commands such as `textDocument/codeLens` and `codeLens/resolve`. Both of which cause an exception to be thrown here

https://github.com/PowerShell/PowerShellEditorServices/blob/41fce39f491d5d351b4ac5864e89857ec070e107/src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs#L144

This is all using very basic configuration of the Monaco Editor and a model URI of `inmemory://model.ps1`.

### PowerShell Version

```console
❯ $PSVersionTable
                                                                                                                        Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Editor Version

```console
Monaco v7.0.7
```

### PowerShell Editor Services Version

```console
v3.20.1


(Invoke-RestMethod https://api.github.com/repos/PowerShell/PowerShellEditorServices/releases/latest).tag_name // v3.20.1
```

### Steps to Reproduce

See forked repository README.md

**Comment by andyleejordan** [comment]
Can you provide a callstack?

**Comment by mhintzke** [comment]
@andyleejordan The callstack and more pertinent information is in the forked repository README.md I linked above. Here is is though:

```csharp
Uncaught Error: Internal Error - System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Microsoft.PowerShell.EditorServices.Services.WorkspaceService.OpenStreamReader(DocumentUri uri) in C:\__w\1\s\src\PowerShellEditorServices\Services\Workspace\WorkspaceService.cs:line 398
   at Microsoft.PowerShell.EditorServices.Services.WorkspaceService.GetFile(DocumentUri documentUri) in C:\__w\1\s\src\PowerShellEditorServices\Services\Workspace\WorkspaceService.cs:line 144
   at Microsoft.PowerShell.EditorServices.Services.WorkspaceService.TryGetFile(DocumentUri documentUri, ScriptFile& scriptFile) in C:\__w\1\s\src\PowerShellEditorServices\Services\Workspace\WorkspaceService.cs:line 211
   at Microsoft.PowerShell.EditorServices.Services.AnalysisService.GetMostRecentCodeActionsForFileAsync(DocumentUri uri) in C:\__w\1\s\src\PowerShellEditorServices\Services\Analysis\AnalysisService.cs:line 218
   at Microsoft.PowerShell.EditorServices.Handlers.PsesCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken) in C:\__w\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\CodeActionHandler.cs:line 49
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()

Error: Internal Error - System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Microsoft.PowerShell.EditorServices.Services.WorkspaceService.OpenStreamReader(DocumentUri uri) in C:\__w\1\s\src\PowerShellEditorServices\Services\Workspace\WorkspaceService.cs:line 398
   at Microsoft.PowerShell.EditorServices.Services.WorkspaceService.GetFile(DocumentUri documentUri) in C:\__w\1\s\src\PowerShellEditorServices\Services\Workspace\WorkspaceService.cs:line 144
   at Microsoft.PowerShell.EditorServices.Services.WorkspaceService.TryGetFile(DocumentUri documentUri, ScriptFile& scriptFile) in C:\__w\1\s\src\PowerShellEditorServices\Services\Workspace\WorkspaceService.cs:line 211
   at Microsoft.PowerShell.EditorServices.Services.AnalysisService.GetMostRecentCodeActionsForFileAsync(DocumentUri uri) in C:\__w\1\s\src\PowerShellEditorServices\Services\Analysis\AnalysisService.cs:line 218
   at Microsoft.PowerShell.EditorServices.Handlers.PsesCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken) in C:\__w\1\s\src\PowerShellEditorServices\Services\TextDocument\Handlers\CodeActionHandler.cs:line 49
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
    at handleResponse (http://localhost:5555/main.bundle.js:1331:48)
    at handleMessage (http://localhost:5555/main.bundle.js:1111:13)
    at processMessageQueue (http://localhost:5555/main.bundle.js:1128:17)
    at http://localhost:5555/main.bundle.js:1100:13
    at http://localhost:5555/main.bundle.js:108245:29
```
