### ISSUE TITLE
SortHierarchicalSymbolsImpl throwing on "We didn't find the child's parent!"

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#2203]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/PowerShellEditorServices/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with _PowerShell Editor Services itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance, and is not an issue with my editor.
- [X] I have verified that I am using the latest version of PowerShell Editor Services.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

```
❯ Process terminated. Assertion failed.
We didn't find the child's parent!
   at Microsoft.PowerShell.EditorServices.Handlers.PsesDocumentSymbolHandler.SortHierarchicalSymbolsImpl(List`1 symbols, CancellationToken cancellationToken) in D:\PowerShellEditorServices\src\PowerShellEditorServices\Services\TextDocument\Handlers\DocumentSymbolHandler.cs:line 87
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### PowerShell Version

```console
HotReload Preview Build
```

### Editor Version

```console
MA
```

### PowerShell Editor Services Version

```console
MA
```

### Steps to Reproduce

mA

### Visuals

MA

### Logs

MA

**Comment by JustinGrote** [comment]
Well now I can't reproduce it, @andyleejordan something to bang on.

**Comment by andyleejordan** [comment]
Resolved by #2084 (v3.14.0) — `SortHierarchicalSymbols` no longer throws (non-throwing assert + corrected sort). Closing as completed.

---
_Drafted by GitHub Copilot (Claude Opus 4.8) at @andyleejordan's request._
