### ISSUE TITLE
Semantic highlighting doesn't apply to text that is typed

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShellEditorServices#2216]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Like the title says, semantic highlighting doesn't work for any new text you type, it only works for the text that was already there when you opened a file. Interestingly the VS code token inspect feature correctly lists the semantic color but the visuals aren't updated. Initially I assumed this was a bug in VS code itself but if I try it with the C# extension it works perfectly fine in VS code so they must be doing something different from this extension.
Here's a clip that demonstrates the issue:

https://github.com/user-attachments/assets/1ea3f679-ad4d-413e-97f1-4e4a17d9b610

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.5
PSEdition                      Core
GitCommitId                    7.5.0-preview.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.5.0
InstanceId       : 0de14edd-e7a3-4dcc-9ad1-f833dc86ffca
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : da-DK
CurrentUICulture : da-DK
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.96.0-insider
19fabc20e35c89915c772116503a079554166a3f
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.5.0
```

### Steps to Reproduce

Enable semantic highlighting with colors that don't match the colors from the textmate highlighting and start typing.

**Comment by JustinGrote** [comment]
Here's a potential clue from bicep:

![Image](https://github.com/user-attachments/assets/66b0d78c-b20f-4883-8538-6935fdf47779)

I'm guessing they made all their requests parallel based instead of serial based, so the serial/parallel switchover cancellation doesn't ever happen.

**Comment by JustinGrote** [comment]
It appears the cancellation of the completionHandler causes an unhandled cancellation exception in our `GetCommandInfoAsync` here:  
[IReadOnlyList<CommandInfo> results = await executionService](https://github.com/PowerShell/PowerShellEditorServices/blob/e26f172efa6ee6aef1de0f64b7f2d0fbbc5d22cd/src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs#L147). 

Whatever is happening there apparently isn't "cleaning up" in the way Omnisharp wants in order to proceed, so the semantic response never gets sent.

It seems to mostly trigger on when you hit a completion when typing with an active completion already in flight to the LSP (as completions can take 300-800ms sometimes).

CC @andyleejordan for help. I'm not quite sure what the coordination is expected to be in the event of a cancellationToken here.

```
Exception has occurred: CLR/System.Threading.Tasks.TaskCanceledException
An exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'A task was canceled.'
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.CommandHelpers.<GetCommandInfoAsync>d__8.MoveNext() in D:\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShell\Utility\CommandHelpers.cs:line 147
   at Microsoft.PowerShell.EditorServices.Handlers.PsesCompletionHandler.<Handle>d__14.MoveNext() in D:\PowerShellEditorServices\src\PowerShellEditorServices\Services\TextDocument\Handlers\CompletionHandler.cs:line 165
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.<Handle>d__0.MoveNext()
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__3.MoveNext()
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
```

**Comment by JustinGrote** [comment]
Can't believe I didn't spot this earlier. In registration our completion handler has been forced to serial mode, and I'm guessing Omnisharp didn't account/test for this.

![Image](https://github.com/user-attachments/assets/e1d7de35-28a5-4026-98e2-800b4b1d6622)

@SeeminglyScience since not all handlers go thru the pipeline like the semantic handler, maybe there's a better way to approach this?

**Comment by JustinGrote** [comment]
Removing the serial does fix it, the cancellation still happens but it doesn't cause the parallel to serial switch (since all commands past didChange are parallel) and doesn't cause the semantic to be cancelled.
