### ISSUE TITLE
GetVersionDetails failing due to empty $env:PROCESSOR_ARCHITECTURE

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#346]
Just looking at a log file and noticed this:
```
1/18/2017 8:12:05 PM [NORMAL] - Method "StartLogging" at line 117 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    PowerShell Editor Services Host v0.0.0.0 starting (pid 22828)...
    
      Host application details:
    
        Name:      Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version:   0.8.0
        Arch:      64-bit
    
      Operating system details:
    
        Version: Microsoft Windows NT 10.0.14393.0
        Arch:    64-bit

1/18/2017 8:12:05 PM [WARNING] - Method "GetVersionDetails" at line 149 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellVersionDetails.cs

    Failed to look up PowerShell version, defaulting to version 5.
    
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<>c__47`1.<ExecuteScriptAndGetItem>b__47_0(PSObject pso)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Enumerable.<OfTypeIterator>d__92`1.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteScriptAndGetItem[TResult](String scriptToExecute, Runspace runspace, TResult defaultValue)
       at Microsoft.PowerShell.EditorServices.Session.PowerShellVersionDetails.GetVersionDetails(Runspace runspace)
```
This on latest bits updated just a little while ago.

**Comment by daviwil** [comment]
Haha, wow, I actually broke it on the VS Code side by sending an empty environment variables object to the process, must have cleared out all the env vars completely.

**Comment by rkeithhill** [comment]
Yeah, probably good to get that fixed before the release.  :-)

**Comment by mrward** [comment]
I am seeing a similar NullReferenceException on the Mac using:

 - PowerShell Editor Services 0.9.0
 - Visual Studio Code 1.8.1
 - PowerShell Core: v6.0.0-alpha.14

```
01/29/2017 10:17:17 [NORMAL] - Method "StartLogging" at line 117 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    PowerShell Editor Services Host v0.0.0.0 starting (pid 613)...
    
      Host application details:
    
        Name:      Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version:   0.9.0
    

01/29/2017 10:17:18 [WARNING] - Method "GetVersionDetails" at line 152 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellVersionDetails.cs

    Failed to look up PowerShell version, defaulting to version 5.
    
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<>c__47`1.<ExecuteScriptAndGetItem>b__47_0(PSObject pso)
       at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
       at System.Linq.Enumerable.<OfTypeIterator>d__33`1.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteScriptAndGetItem[TResult](String scriptToExecute, Runspace runspace, TResult defaultValue)
       at Microsoft.PowerShell.EditorServices.Session.PowerShellVersionDetails.GetVersionDetails(Runspace runspace)
```

**Comment by daviwil** [comment]
Thanks for letting me know!  I'll get a patch update shipped in a few days.
