### ISSUE TITLE
While debugging, VariableDetails.GetChildren should be run on the pipeline thread

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#37]
Keith uncovered this issue while debugging a script with the following lines:

``` powershell
    $p = Get-Process
    $ps0 = $p[0]
```

If you stop the debugger after the `$ps0` line and hover the mouse cursor over that variable, the debug server will crash with the following stack trace:

```
    System.Management.Automation.GetValueInvocationException: Exception getting "Path": "There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: $this.Mainmodule.FileName" ---> System.Management.Automation.PSInvalidOperationException: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: $this.Mainmodule.FileName
       at System.Management.Automation.ScriptBlock.GetContextFromTLS()
       at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
       at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
       at System.Management.Automation.PSScriptProperty.InvokeGetter(Object scriptThis)
       --- End of inner exception stack trace ---
       at System.Management.Automation.PSScriptProperty.InvokeGetter(Object scriptThis)
       at System.Management.Automation.PSScriptProperty.get_Value()
       at Microsoft.PowerShell.EditorServices.VariableDetails.<GetChildren>b__0(PSPropertyInfo p) in c:\dev\PowerShellEditorServices\src\PowerShellEditorServices\Debugging\VariableDetails.cs:line 189
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
       at Microsoft.PowerShell.EditorServices.VariableDetails.GetChildren(Object obj) in c:\dev\PowerShellEditorServices\src\PowerShellEditorServices\Debugging\VariableDetails.cs:line 186
       at Microsoft.PowerShell.EditorServices.VariableDetails.GetChildren() in c:\dev\PowerShellEditorServices\src\PowerShellEditorServices\Debugging\VariableDetails.cs:line 138
       at Microsoft.PowerShell.EditorServices.DebugService.GetVariables(Int32 variableReferenceId) in c:\dev\PowerShellEditorServices\src\PowerShellEditorServices\Debugging\DebugService.cs:line 167
       at Microsoft.PowerShell.EditorServices.Host.DebugAdapter.<HandleVariablesRequest>d__3c.MoveNext() in c:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Host\DebugAdapter.cs:line 313

```

It seems like VariableDetails.GetChildren needs to be run on the debugger pipeline thread to ensure that any runspace operations are run in the correct context.

**Comment by tylerl0706** [comment]
The repro steps for this confuse me a bit 

> stop the debugger after the $ps0 line

Do you mean that you need a breakpoint after that line?

**Comment by daviwil** [comment]
Yeah, just have another line after with `Write-Host $ps0` or something and set a breakpoint on it.  Judging from what I read here some things I did last year may have fixed this issue.  Definitely try to repro it and see if it works now.

Just realized, this bug is super old!

**Comment by filmihaylov** [comment]
Hi not sure if i am getting the same issue. My exception is (System.Management.Automation.GetValueInvocationException: 'Exception getting "Path": "There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: $this.Mainmodule.FileName"'
)

when I try this code : ->
 using (PowerShell PowershellInstance = PowerShell.Create())
            {
                List<ProcessDTO> processDTOList = new List<ProcessDTO>();
                PowershellInstance.AddCommand("Get-Process");
                Collection<PSObject> PSOutput = PowershellInstance.Invoke();

                foreach (PSObject outputItem in PSOutput)
                {
                    if (outputItem != null)
                    {

                        var processDTOOBJECT = JsonConvert.SerializeObject(outputItem.Properties.ToDictionary(k => k.Name, v => v.Value));

**Comment by tylerl0706** [comment]
@filmihaylov from what I can tell, that code you pasted is C# and you're trying to create a runspace and execute `Get-Process` in it. How are you running the code? Are you using VSCode? 

This doesn't sound like an issue with the PowerShell extension for VSCode. I would recommend posting on [StackOverflow](http://stackoverflow.com/).

**Comment by rkeithhill** [comment]
I can't repro the original bug anymore. I say close it.

**Comment by tylerl0706** [comment]
Sounds good! Please don't hesitate to open a new one if you see the issue.
