### ISSUE TITLE
invokeExtensionCommand is adding an additional double quote to currentFilePath and crashing session

### ISSUE THREAD

**Issue by gerane** [PowerShell/PowerShellEditorServices#390]
Code Version: 1.11.0-insider
OS Version: Windows 10

When launching Editor Commands, for some reason it has started appending an additional double quote to the end of the path and causing an error that crashes the PowerShell session. It seems random and not related to the path. I have had the same path work and then stop working. When it starts breaking, it almost seems like every file in the project will start crashing the session even after reload.

Here is the log output from executing the command from a few different projects

## Project 1

This was from the 15th,  and actually cleared up if I renamed **BlockedEmail.ps1** to **Update-BlockedSenders.ps1**, but it started again today for a different file and I haven't changed anything that I can think of. I included the newer logs further down. I didn't see anything relevant in the logs before the error, but if you need them let me know. 

PSES log

```
3/15/2017 9:08:17 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 3,
      "method": "powerShell/invokeExtensionCommand",
      "params": {
        "name": "PowerShellEditorServices.OpenProfileList",
        "context": {
          "currentFilePath": "c:\\Github\\OutlookEmailFilter\\BlockedEmail.ps1\"",
          "cursorPosition": {
            "line": 18,
            "character": 0
          },
          "selectionRange": {
            "start": {
              "line": 18,
              "character": 0
            },
            "end": {
              "line": 18,
              "character": 0
            }
          }
        }
      }
    }

3/15/2017 9:08:17 AM [ERROR] - Method "OnListenTaskCompleted" at line 337 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.GetFullPathInternal(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.ResolveFilePath(String filePath)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass24_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.GetFullPathInternal(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.ResolveFilePath(String filePath)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass24_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
```
vscode-powershell log

```
    pid: 944
    args: C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.0\scripts\Start-EditorServices.ps1 -EditorServicesVersion '0.10.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '0.10.0' -BundledModulesPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.0\modules' -EnableConsoleRepl -LogLevel 'Verbose' -LogPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.0\logs\1489584275-26d40114-48fe-486b-9025-a7e90c99e19c1489584257797\EditorServices.log' -SessionDetailsPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.0\sessions\PSES-VSCode-43692' 


powershell.exe started --
    exe: C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe
Connecting to language service on port 21354...

Language service connected.

powershell.exe terminated or terminal UI was closed
```

## Project 2

This one is the one that started working again on the 15th after renamed that one script. This morning it started erroring again, but not only will it error on the file in the error, but it now errors on the **Update-BlockedSenders.ps1** that fixed the issue the other day.

PSES log

```
3/17/2017 9:01:42 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 3,
      "method": "powerShell/invokeExtensionCommand",
      "params": {
        "name": "KaceProjects.OpenGithubRepo",
        "context": {
          "currentFilePath": "c:\\Github\\OutlookEmailFilter\\Test-Outlook.ps1\"",
          "cursorPosition": {
            "line": 23,
            "character": 16
          },
          "selectionRange": {
            "start": {
              "line": 23,
              "character": 16
            },
            "end": {
              "line": 23,
              "character": 16
            }
          }
        }
      }
    }

3/17/2017 9:01:42 AM [ERROR] - Method "OnListenTaskCompleted" at line 337 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.GetFullPathInternal(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.ResolveFilePath(String filePath)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass24_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.GetFullPathInternal(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.ResolveFilePath(String filePath)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass24_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
```

vscode-powershell log

```
[9:0:12] Language server starting...
powershell.exe started --
    pid: 916
    exe: C:\Windows\Sysnative\WindowsPowerShell\v1.0\powershell.exe
    args: C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\scripts\Start-EditorServices.ps1 -EditorServicesVersion '0.10.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '0.10.1' -BundledModulesPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\modules' -EnableConsoleRepl -LogLevel 'Verbose' -LogPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\logs\1489759212-38ac61d2-8487-4f01-9b7d-fe636676dcef1489759208330\EditorServices.log' -SessionDetailsPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\sessions\PSES-VSCode-4920' 


[9:0:16] Language server started.
Connecting to language service on port 21091...

Language service connected.

powershell.exe terminated or terminal UI was closed
```

## Project 3

This project has over 100 files named **Deploy-Application.ps1** and this project wasn't causing problem yesterday. I can open another of those **Deploy-Application.ps1** files and run another Ediotor command and get the same error.

PSES log

```
3/17/2017 9:10:19 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 99,
      "method": "powerShell/invokeExtensionCommand",
      "params": {
        "name": "DevProjects.PublishCurrentPackage",
        "context": {
          "currentFilePath": "c:\\Github\\DevPackages\\Chrome\\Toolkit\\Deploy-Application.ps1\"",
          "cursorPosition": {
            "line": 267,
            "character": 0
          },
          "selectionRange": {
            "start": {
              "line": 267,
              "character": 0
            },
            "end": {
              "line": 267,
              "character": 0
            }
          }
        }
      }
    }

3/17/2017 9:10:19 AM [ERROR] - Method "OnListenTaskCompleted" at line 337 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.GetFullPathInternal(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.ResolveFilePath(String filePath)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass24_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.GetFullPathInternal(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.ResolveFilePath(String filePath)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass24_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
```

vscode-powershell log 

```
[9:2:58] Language server starting...
powershell.exe started --
    pid: 868
    exe: C:\Windows\Sysnative\WindowsPowerShell\v1.0\powershell.exe
    args: C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\scripts\Start-EditorServices.ps1 -EditorServicesVersion '0.10.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '0.10.1' -BundledModulesPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\modules' -EnableConsoleRepl -LogLevel 'Verbose' -LogPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\logs\1489759378-1b89dec5-6579-46c1-a936-d711ba6bfc961489759375411\EditorServices.log' -SessionDetailsPath 'C:\Users\user\.vscode-insiders\extensions\ms-vscode.powershell-0.10.1\sessions\PSES-VSCode-4920' 


[9:3:2] Language server started.
Connecting to language service on port 24563...

Language service connected.

powershell.exe terminated or terminal UI was closed
```

**Comment by gerane** [comment]
@daviwil This is also happening to filepaths when using f5 to debug\execute open script. I get the following error

```powershell
The term 'c:\Users\User\OneDrive\Documents\Azure\Working\Install-AzureVPN.ps1"' is not recognized as the name of a cmdlet, function, script file, or operab
le program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:0 char:0
```
You can see where it has had an extra double quote tacked on to the end. Here are the logs from running this.

https://gist.github.com/gerane/574fc1b037294009d244b81e6730f1a4

**Comment by daviwil** [comment]
I'll see if I can get this fixed for the next update this week.

**Comment by daviwil** [comment]
This must be something VS Code's doing but I honestly have no idea how...  I tried to reproduce it on my machine but couldn't.  When I run an editor command, that file path is coming directly from VS Code's API without any further manipulation on my end.  The fact that it also happens when you run the debugger against the current script makes me think VS Code is returning a path with a quotation mark in it.

Do you still see this in the most recent Insiders builds?

**Comment by tylerl0706** [comment]
Hey @gerane, can you still repro this? This issue has been quiet for some time and I'd love to close it if it's no longer an issue!
