### ISSUE TITLE
Buffer Error when pasting command that is longer than a single line

### ISSUE THREAD

**Issue by gerane** [PowerShell/PowerShellEditorServices#410]
This was really the only part of the logs that had anything to so with the error. If I paste path of a command into the terminal that is longer than a single line, I get this error thrown.

This is what I was pasting and it is reproducible for me.

`C:\Github\Secure-Host-Baseline-master\Windows\Group Policy Objects\Computer\{A2A38432-E322-437F-9975-B7CC7F16F4AA}\DomainSysvol\GPO\Machine\registry.pol`

```
3/31/2017 4:46:09 PM [ERROR] - Method "StartReplLoop" at line 334 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Console\ConsoleService.cs

    Caught exception while reading command line
    
    System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
    Parameter name: top
    Actual value was 3000.
       at System.Console.SetCursorPosition(Int32 left, Int32 top)
       at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
       at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Console.ConsoleService.<StartReplLoop>d__22.MoveNext()

```

**Comment by daviwil** [comment]
Hmmm weird, thanks for that one, haven't seen it before.

**Comment by gerane** [comment]
No, I've been seeing it occasionally, but finally noticed it only seemed to happen when I pasted.

I've also noticed that pasting into the terminal multilinear commands is not working. It's doing the same thing psreadline does.

**Comment by daviwil** [comment]
My prompt implementation doesn't support multi-line input yet, I'm waiting for PSReadline integration to get that going.  Don't have enough time to make my own implementation at the moment.

**Comment by gerane** [comment]
Ahh, ok that makes sense. I keep forgetting and copy/paste out of habit still lol.

**Comment by tylerl0706** [comment]
I can't repro this anymore 🙂 I'm going to close it - feel free to open a new one if you're still seeing the issue.

**Comment by daviwil** [comment]
The thing I forgot to mention here is that there's a specific reason for the issue: having enough lines in your terminal history (3000+) and then overflowing the column width of the terminal.  If you make a script that writes out 3000 lines then past a super long line into the terminal, I think it'll crash.

**Comment by shivamjjha** [comment]
I also faced the same issue:

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 9 Keys:
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
![Screenshot 2020-12-07 211006](https://user-images.githubusercontent.com/44032634/101371454-c686ad00-38d0-11eb-9771-10f5b7be836a.jpg)

Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by rjmholt** [comment]
@shivamjjha I believe that's a PSReadLine issue, as it says in the error message.

I'm going to close this issue since it predates our move to PSReadLine, which is now responsible for this functionality.
