### ISSUE TITLE
Random ValueFromPipelineByValue error in PSIC while editing script

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#462]
VSCode 1.12.2, Ext: 1.1.0, Windows 10 CU.

Here is the error that showed up in the PSIC:
```
Caught error while waiting for EditorServicesHost to complete:
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.WaitForExit()
   at CallSite.Target(Closure , CallSite , Object )
One or more errors occurred.

Property 'ValueFromPipelineByValue' cannot be found for type 'System.Management.Automation.CmdletBindingAttribute'.
   at System.Management.Automation.Language.Compiler.NewParameterAttribute(AttributeAst ast)
   at System.Management.Automation.Language.Compiler.GetAttribute(AttributeAst attributeAst)
   at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
   at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
   at System.Management.Automation.CompiledScriptBlockData.get_CmdletBindingAttribute()
   at System.Management.Automation.CommandMetadata..ctor(ScriptBlock scriptblock, String commandName, ExecutionContext context)
   at System.Management.Automation.FunctionInfo.get_CommandMetadata()
   at System.Management.Automation.CommandInfo.GenerateCommandParameterSetInfo()
   at System.Management.Automation.CommandInfo.get_ParameterSets()
   at Microsoft.PowerShell.EditorServices.LanguageService.<FindParameterSetsInFile>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleSignatureHelpRequest>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
   at System.Threading.Tasks.Task.Execute()
```
[1495579816-646549eb-cb5a-4a84-9336-af14a96c21161495495298087.zip](https://github.com/PowerShell/PowerShellEditorServices/files/1023928/1495579816-646549eb-cb5a-4a84-9336-af14a96c21161495495298087.zip)

**Comment by daviwil** [comment]
Hmmm, weird, haven't seen that before.  Should be easy to fix though.

**Comment by rkeithhill** [comment]
This is a bug in my script but it probably shouldn't have caused the above exception.  Here's the bad script:
```posh
    param(
        [Parameter(Mandatory, Position = 0, ValueFromPipelineByValue)]
        [ValidateNotNull()]
        [DomainModel.LicenseService.LicenseHost[]]
        $LicenseHost
    )
```
`ValueFromPipelineByValue` is not a valid property.

**Comment by daviwil** [comment]
Cool, that's helpful!
