### ISSUE TITLE
PS Core 6.0 Beta3 doesn't load in v1.4.0

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#529]
Just installed PS Core Beta 3 on Windows 10 CU.  Fire up VSCode 1.13.0 with 1.4.0 of the PS extension, switched to PS Core 6.0 Beta 3 and got this error:
```
PowerShell Integrated Console



An error occurred while starting PowerShell Editor Services:

Exception calling "StartLanguageService" with "2" argument(s): "Could not load file or assembly 'Microsoft.Po
werShell.EditorServices.Protocol, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file
specified."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception excep
tion)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)

   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Could not load file or assembly 'Microsoft.PowerShell.EditorServices.Protocol, Version=1.4.0.0, Culture=neutral, PublicKey
Token=null'. The system cannot find the file specified.
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLanguageService(Int32 languageServicePort, ProfileP
aths profilePaths)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

**Comment by daviwil** [comment]
You're fast ;)  Luckily the team caught that for me this morning and I'll be shipping an update with a fix in an hour or so.

**Comment by rkeithhill** [comment]
Is it something about `-FeatureFlags` not getting the expected empty string array arg?

**Comment by daviwil** [comment]
Nah, it's that I'm not explicitly loading the Protocol DLL using Add-Type and the change they made to the AssemblyLoadContext isn't auto-loading it anymore.  It's a simple fix thankfully

**Comment by rkeithhill** [comment]
Ah, so the issue I see trying to run the command from the PowerShell console is just a red herring then.  OK. I'll await the fix.  :-)

**Comment by daviwil** [comment]
If you want a quick fix for now you can just edit PowerShellEditorServices.psm1 to add the Add-Type line for Protocol

**Comment by rkeithhill** [comment]
FWIW I thought it was maybe related to the breaking change in powershell.exe positional parameters ie. position 0 is now -File instead of -Command. 

RE the fix, I can wait.
