### ISSUE TITLE
"Parameter name: Position 25:16 is outside of the column range of 1 to 15." exception on "textDocument/didChange"

### ISSUE THREAD

**Issue by ant-druha** [PowerShell/PowerShellEditorServices#589]
Hello dear team. I'm trying to adopt PS Editor Service for use with the LSP, via the [intellij-lsp](https://github.com/gtache/intellij-lsp/tree/master/intellij-lsp) plugin (which implements [LSP4J](https://github.com/eclipse/lsp4j) - Java binding for the LSP for IntelliJ platform).

I'm launching the service from ps console with the command:
```
/Users/Andrey/.vscode/extensions/ms-vscode.powershell-1.5.1/scripts/Start-EditorServices.ps1 -EditorServicesVersion '1.5.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.5.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/Andrey/.vscode/extensions/ms-vscode.powershell-1.5.1/modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'path/to/EditorServices.log' -SessionDetailsPath 'path/to/session_details_fila' -FeatureFlags @()
```

But at some point (when I do any change to my .ps1 file) I'm getting this exception which terminates the Editor Service session:

```
12/28/2017 19:47:09 [ERROR] - Method "DispatchMessage" at line 147 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher: No handler registered for Event type 'workspace/didChangeWatchedFiles'

12/28/2017 19:47:45 [DIAGNOSTIC] - Method "ReadMessage" at line 114 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "method": "textDocument/didChange",
      "params": {
        "textDocument": {
          "version": 0,
          "uri": "file:///Users/Andrey/IdeaProjects/PS-fo-run/src/test_args.ps1"
        },
        "contentChanges": [
          {
            "range": {
              "start": {
                "line": 24,
                "character": 14
              },
              "end": {
                "line": 24,
                "character": 15
              }
            },
            "rangeLength": 1,
            "text": "."
          }
        ]
      }
    }

12/28/2017 19:47:45 [VERBOSE] - Method "ReadMessage" at line 123 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    Received Event 'textDocument/didChange'

12/28/2017 19:47:45 [VERBOSE] - Method "ResolveFilePath" at line 366 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs

    Resolved path: /Users/Andrey/IdeaProjects/PS-fo-run/src/test_args.ps1

12/28/2017 19:47:45 [ERROR] - Method "OnListenTaskCompleted" at line 391 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs

    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.
    Parameter name: Position 25:16 is outside of the column range of 1 to 15.) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
    Parameter name: Position 25:16 is outside of the column range of 1 to 15.
       at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
    Parameter name: Position 25:16 is outside of the column range of 1 to 15.
       at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()<---
    

12/28/2017 19:47:45 [ERROR] - Method "ProtocolEndpoint_UnhandledException" at line 418 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.
```
I've attached full log from the session. 
[EditorServices_IJ.log](https://github.com/PowerShell/PowerShellEditorServices/files/1591779/EditorServices_IJ.log)

Could yo advise, why could this happen? Does PS Language server support LSP 3 version of the protocol? Thank you.

**Comment by rkeithhill** [comment]
From the PSES source (LanguageServer.GetFileChangeDetails():
```csharp
// The protocol's positions are zero-based so add 1 to all offsets
```
Make sure your document positions are zero-based because, PSES internally adds 1 so that it matches up with the PowerShell AST which uses one-based positions in its extents.

**Comment by ant-druha** [comment]
Appreciate the prompt response. The document positions are zero-based.

I see that the max column [is computed](https://github.com/PowerShell/PowerShellEditorServices/blob/cb68635231ecd92412527e6e38306b1143ac6f73/src/PowerShellEditorServices/Workspace/ScriptFile.cs#L275) like:
```
int maxColumn = lineString.Length > 0 ? lineString.Length + 1 : 1;
```
I don't quite understand how the [`fileChange.EndOffset`](https://github.com/PowerShell/PowerShellEditorServices/blob/cb68635231ecd92412527e6e38306b1143ac6f73/src/PowerShellEditorServices/Workspace/ScriptFile.cs#L293) is expected to be less than current line length, since the change **adds** characters to current line. So to me it looks like it should be 
```
int maxColumn = (lineString.Length > 0 ? lineString.Length + 1 : 1) + fileChange.InsertString.Lenght;
```

Obviously I'm missing something. Can you clarify? Thank you.

**Comment by rkeithhill** [comment]
> I don't quite understand how the fileChange.EndOffset is expected to be less than current line length

It is expected to be less than current line length **+ 1**.  See the comment:
```csharp
// The maximum column is either **one past** the length of the string
// or 1 if the string is empty.
```

**Comment by ant-druha** [comment]
After I've looked at `ApplyChange` method usages closely I've realised that the the client sends not correct start/end parameters. I've changed it now, and it seems to be working better. Though there are still errors in some cases, which I'm trying to debug now (not very easy to get the script content from the server side). 
Thank you for your replies!

**Comment by ant-druha** [comment]
Got it all now, it is because of tabs: IJ logical column position takes **tab length** into account. But the column values are justified by the line length.
I this we can close this:) Thanks again.

**Comment by tylerl0706** [comment]
Awesome! Glad you're unblocked. Let us know when you have a demo of the IJ extension that uses PSES. I'd love to try it out and provide feedback 🙂
