### ISSUE TITLE
PSES crashes when computing references for files under: `inmemory://`

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/PowerShellEditorServices#711]
Monaco uses this concept of `inmemory://` files and PSES doesn't seem to like that. It crashes on [this line](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs#L108)

```
2018-07-26 00:25:52.294 [VERBOSE] /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/MessageReader.cs: In method 'ReadMessage', line 123:
    Received Request 'codeLens/resolve' with id 3

2018-07-26 00:25:52.303 [VERBOSE] /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices/Workspace/Workspace.cs: In method 'ResolveFilePath', line 378:
    Resolved path: inmemory://model.ps1

2018-07-26 00:25:52.337 [ERROR] /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Invalid URI: The hostname could not be parsed.) ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
       at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
       at System.Uri..ctor(String uriString)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.GetFileUri(String filePath) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs:line 111
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<>c.<ResolveCodeLensAsync>b__4_1(SymbolReference r) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs:line 74
       at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.ResolveCodeLensAsync(CodeLens codeLens, CancellationToken cancellationToken) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs:line 67
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.HandleCodeLensResolveRequest(CodeLens codeLens, RequestContext`1 requestContext) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/CodeLensFeature.cs:line 139
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs:line 160
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs:line 379
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContext.cs:line 49
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContextThread.cs:line 66
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.UriFormatException: Invalid URI: The hostname could not be parsed.
       at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
       at System.Uri..ctor(String uriString)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.GetFileUri(String filePath) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs:line 111
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<>c.<ResolveCodeLensAsync>b__4_1(SymbolReference r) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs:line 74
       at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.ResolveCodeLensAsync(CodeLens codeLens, CancellationToken cancellationToken) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs:line 67
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.HandleCodeLensResolveRequest(CodeLens codeLens, RequestContext`1 requestContext) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Host/CodeLens/CodeLensFeature.cs:line 139
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs:line 160
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs:line 379
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger) in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContext.cs:line 49
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in /home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContextThread.cs:line 66
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---

```

**Comment by tylerl0706** [comment]
Fixed in 1.8.2
