### ISSUE TITLE
Crash when deleting lines

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#739]
Deleted multiple empty lines from the end of a file in `vim`-mode and got this crash:

```
2018-09-04 11:40:41.973 [ERROR] /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
       at System.Collections.Generic.List`1.get_Item(Int32 index)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices/Workspace/ScriptFile.cs:line 399
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs:line 555
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs:line 110
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs:line 142
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs:line 379
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContext.cs:line 49
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContextThread.cs:line 66
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
       at System.Collections.Generic.List`1.get_Item(Int32 index)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices/Workspace/ScriptFile.cs:line 399
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs:line 555
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs:line 110
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs:line 142
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs:line 379
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger) in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContext.cs:line 49
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices/Utility/AsyncContextThread.cs:line 66
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
    

2018-09-04 11:40:41.973 [ERROR] /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/src/PowerShellEditorServices.Host/EditorServicesHost.cs: In method 'ProtocolEndpoint_UnhandledException', line 435:
    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.
```

**Comment by rkeithhill** [comment]
This looks eerily familiar.  I think this was the type of error I had tried to fix in the ValidatePosition code.  Feels like we might have a "whack a mole" bug here.  :-)

**Comment by rjmholt** [comment]
I was afraid of that -- I thought I'd handled it cleverly by only allowing a +1 offset and then testing for that specific case, but I think I haven't quite done it right...
