### ISSUE TITLE
NullReferenceException from LanguageService.GetAliases()

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#770]
Well, it's a few levels down from that but I suspect it originated from GetAliases:
```
2018-10-08 20:40:00.354 [NORMAL] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: In method 'StartLogging', line 150:
    PowerShell Editor Services Host v2.0.0.0 starting (pid 19308)...
    
      Host application details:
    
        Name:      Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version:   2.0.0
        Arch:      64-bit

…

2018-10-08 20:40:05.779 [VERBOSE] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: In method 'ExecuteCommand', line 622:
    Attempting to execute command(s):
    
        
            [System.Diagnostics.DebuggerHidden()]
            [System.Diagnostics.DebuggerStepThrough()]
            param()
            return [Microsoft.PowerShell.PSConsoleReadLine, Microsoft.PowerShell.PSReadLine2, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]::ReadLine(
                $Host.Runspace,
                $ExecutionContext,
                $args[0]) System.Threading.CancellationToken
    

2018-10-08 20:40:05.780 [VERBOSE] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Workspace\Workspace.cs: In method 'ResolveFilePath', line 382:
    Resolved path: c:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\module\PowerShellEditorServices\Start-EditorServices.ps1

2018-10-08 20:40:05.806 [VERBOSE] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: In method 'WriteMessage', line 61:
    Writing Event 'powerShell/executionStatusChanged'

2018-10-08 20:40:05.806 [VERBOSE] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: In method 'WriteMessage', line 61:
    Writing Event 'powerShell/executionStatusChanged'

2018-10-08 20:40:05.807 [VERBOSE] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: In method 'WriteMessage', line 61:
    Writing Event 'powerShell/executionStatusChanged'

2018-10-08 20:40:05.808 [VERBOSE] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Utility\ThreadSynchronizationContext.cs: In method 'Post', line 64:
    Attempted to post message to synchronization context after it's already completed

2018-10-08 20:40:05.976 [ERROR] C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteCommand[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs:line 742
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteCommand[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs:line 787
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteCommand[TResult](PSCommand psCommand, Boolean sendOutputToHost, Boolean sendErrorToHost) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs:line 424
       at Microsoft.PowerShell.EditorServices.LanguageService.GetAliases() in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Language\LanguageService.cs:line 733
       at Microsoft.PowerShell.EditorServices.LanguageService.FindReferencesOfSymbol(SymbolReference foundSymbol, ScriptFile[] referencedFiles, Workspace workspace) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Language\LanguageService.cs:line 326
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.ResolveCodeLensAsync(CodeLens codeLens, CancellationToken cancellationToken) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Host\CodeLens\ReferencesCodeLensProvider.cs:line 85
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.HandleCodeLensResolveRequest(CodeLens codeLens, RequestContext`1 requestContext) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Host\CodeLens\CodeLensFeature.cs:line 176
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 160
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 379
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContext.cs:line 49
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContextThread.cs:line 66
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteCommand[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs:line 742
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteCommand[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs:line 787
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteCommand[TResult](PSCommand psCommand, Boolean sendOutputToHost, Boolean sendErrorToHost) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs:line 424
       at Microsoft.PowerShell.EditorServices.LanguageService.GetAliases() in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Language\LanguageService.cs:line 733
       at Microsoft.PowerShell.EditorServices.LanguageService.FindReferencesOfSymbol(SymbolReference foundSymbol, ScriptFile[] referencedFiles, Workspace workspace) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Language\LanguageService.cs:line 326
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.ResolveCodeLensAsync(CodeLens codeLens, CancellationToken cancellationToken) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Host\CodeLens\ReferencesCodeLensProvider.cs:line 85
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.HandleCodeLensResolveRequest(CodeLens codeLens, RequestContext`1 requestContext) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Host\CodeLens\CodeLensFeature.cs:line 176
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 160
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 379
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger) in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContext.cs:line 49
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in C:\projects\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContextThread.cs:line 66
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
```
BTW it would be nice if we could get the full version (including the prerelease suffix) in the log file.

**Comment by rjmholt** [comment]
This looks like an `AliasInfo` object returned from `invokeCommand.GetCommands("*", CommandTypes.Alias, true)` was `null`...

Do you have a small repro scenario @rkeithhill?

**Comment by rjmholt** [comment]
Hmmm, actually I think the above is wrong. I'm still trying to make sense of this stack trace -- it doesn't look like `PowerShellContext.ExecuteCommand()` is called directly from `LanguageService.GetAliases()`.

**Comment by rjmholt** [comment]
@rkeithhill By full version, do you mean the appveyor release suffix? I'm not quite sure how we'd get that in... Maybe we can set it as an env var, pass it into the csproj and find a way to embed it as a compile-time constant?

**Comment by rjmholt** [comment]
https://stackoverflow.com/questions/4450231/can-i-make-a-constant-from-a-compile-time-env-variable-in-csharp

**Comment by rjmholt** [comment]
@SeeminglyScience thinks this is the same issue: https://github.com/PowerShell/PowerShellEditorServices/issues/759

**Comment by rkeithhill** [comment]
> Do you have a small repro scenario @rkeithhill?

Unfortunately, no.

**Comment by andschwa** [comment]
Hey I'm going to close this four year old bug since `GetAliases` got rewritten.
