### ISSUE TITLE
NullReferenceException crash in Preview 2.0.1

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#900]
Saw this crash switching from pwsh 6.1 to WPS 5.1 while the Examples folder was open:

```
2019-03-29 22:22:32.037 [VERBOSE] tid:26 in 'ExecuteCommandAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 648
    Attempting to execute command(s):
    
        
                [System.Diagnostics.DebuggerHidden()]
                [System.Diagnostics.DebuggerStepThrough()]
                param()
                return [Microsoft.PowerShell.PSConsoleReadLine, Microsoft.PowerShell.PSReadLine2, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]::ReadLine(
                    $Host.Runspace,
                    $ExecutionContext,
                    $args[0]) System.Threading.CancellationToken
    

2019-03-29 22:22:32.094 [VERBOSE] tid:19 in 'ReadMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs: line 138
    Received Request 'codeLens/resolve' with id 5

2019-03-29 22:22:32.116 [VERBOSE] tid:19 in 'ResolveFilePath' C:\PowerShellEditorServices\src\PowerShellEditorServices\Workspace\Workspace.cs: line 484
    Resolved path: c:\Users\Keith\.vscode-insiders\extensions\ms-vscode.powershell-preview-2.0.1\examples\DebugTest.ps1

2019-03-29 22:22:32.216 [VERBOSE] tid:19 in 'WriteMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: line 88
    Writing Event 'powerShell/executionStatusChanged'

2019-03-29 22:22:32.216 [VERBOSE] tid:19 in 'WriteMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: line 88
    Writing Event 'powerShell/executionStatusChanged'

2019-03-29 22:22:32.217 [VERBOSE] tid:25 in 'Post' C:\PowerShellEditorServices\src\PowerShellEditorServices\Utility\ThreadSynchronizationContext.cs: line 64
    Attempted to post message to synchronization context after it's already completed

2019-03-29 22:22:32.223 [ERROR] tid:3 in 'OnListenTaskCompleted' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: line 391
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.PSConsoleReadLine.ForcePSEventHandling()
       at Microsoft.PowerShell.EditorServices.Session.InvocationEventQueue.<SetInvocationRequestAsync>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Session.InvocationEventQueue.<ExecuteCommandOnIdleAsync>d__9`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommandAsync>d__75`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommandAsync>d__75`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommandAsync>d__73`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.LanguageService.<GetAliasesAsync>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.LanguageService.<FindReferencesOfSymbolAsync>d__19.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<ResolveCodeLensAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.<HandleCodeLensResolveRequestAsync>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessageAsync>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessagesAsync>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.PSConsoleReadLine.ForcePSEventHandling()
       at Microsoft.PowerShell.EditorServices.Session.InvocationEventQueue.<SetInvocationRequestAsync>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Session.InvocationEventQueue.<ExecuteCommandOnIdleAsync>d__9`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommandAsync>d__75`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommandAsync>d__75`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommandAsync>d__73`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.LanguageService.<GetAliasesAsync>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.LanguageService.<FindReferencesOfSymbolAsync>d__19.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.ReferencesCodeLensProvider.<ResolveCodeLensAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.CodeLenses.CodeLensFeature.<HandleCodeLensResolveRequestAsync>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessageAsync>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessagesAsync>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()<---
    

2019-03-29 22:22:32.224 [ERROR] tid:3 in 'ProtocolEndpoint_UnhandledException' C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 490
    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.
```

**Comment by rkeithhill** [comment]
Also see this the `vscode-powershell.log` file:
```
3/29/2019 10:22:19 PM [NORMAL] - Language server starting --
3/29/2019 10:22:19 PM [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
3/29/2019 10:22:19 PM [NORMAL] -     args: C:\Users\Keith\.vscode-insiders\extensions\ms-vscode.powershell-preview-2.0.1\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2.0.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\Keith\.vscode-insiders\extensions\ms-vscode.powershell-preview-2.0.1\modules' -EnableConsoleRepl -LogLevel 'Verbose' -LogPath 'C:\Users\Keith\.vscode-insiders\extensions\ms-vscode.powershell-preview-2.0.1\logs\1553919739-c0ce5301-6d30-4dea-b511-2985761c22041553919282001\EditorServices.log' -SessionDetailsPath 'C:\Users\Keith\.vscode-insiders\extensions\ms-vscode.powershell-preview-2.0.1\sessions\PSES-VSCode-10164-198301' -FeatureFlags @('PSReadLine')
3/29/2019 10:22:20 PM [NORMAL] - powershell.exe started, pid: 6988
3/29/2019 10:22:25 PM [NORMAL] - Language server started.
3/29/2019 10:22:25 PM [NORMAL] - {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_uu4xdjsx.5r5","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_hgwcxcws.340"}
3/29/2019 10:22:25 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_uu4xdjsx.5r5...
3/29/2019 10:22:25 PM [NORMAL] - Language service connected.
3/29/2019 10:22:34 PM [NORMAL] - powershell.exe terminated or terminal UI was closed
3/29/2019 10:22:35 PM [VERBOSE] - Formatting on type at position {"line":1,"character":0} - file:///c%3A/Users/Keith/.vscode-insiders/extensions/ms-vscode.powershell-preview-2.0.1/examples/DebugTest.ps1...
```
I do have editor setting in my settings file: `"editor.formatOnType": true`.

**Comment by rkeithhill** [comment]
[EditorServices.zip](https://github.com/PowerShell/PowerShellEditorServices/files/3025140/EditorServices.zip)

**Comment by andyleejordan** [comment]
Obsolete — all classes referenced in this 2.0.1 crash were deleted in the 3.0 rewrite. Closing; please file a fresh report if reproducible on v4.x.

---
_Drafted by GitHub Copilot (Claude Opus 4.8) at @andyleejordan's request._
