### ISSUE TITLE
Preview 2.0.1 crash - InvalidPipeStateException

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#907]
Got this after being away from my PC all day, came back, woke up the PC from sleep and was greeted by this error with the preview:
```
2019-04-03 09:59:22.037 [VERBOSE] tid:12 in 'ExecuteCommandAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 648
    Attempting to execute command(s):
    
        prompt
    

2019-04-03 09:59:22.038 [VERBOSE] tid:12 in 'OnSessionStateChanged' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 1695
    Session state changed --
    
        Old state: Ready
        New state: Running
        Result: NotFinished

2019-04-03 09:59:23.932 [VERBOSE] tid:12 in 'OnSessionStateChanged' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 1695
    Session state changed --
    
        Old state: Running
        New state: Ready
        Result: Completed

2019-04-03 09:59:23.932 [VERBOSE] tid:12 in 'ExecuteCommandAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 724
    Execution completed successfully.

2019-04-03 09:59:23.933 [VERBOSE] tid:21 in 'WriteMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: line 88
    Writing Event 'powerShell/executionStatusChanged'
    
    {
      "jsonrpc": "2.0",
      "method": "powerShell/executionStatusChanged",
      "params": {
        "executionOptions": {
          "writeOutputToHost": false,
          "writeErrorsToHost": false,
          "addToHistory": false,
          "interruptCommandPrompt": false,
          "writeInputToHost": false
        },
        "executionStatus": 4,
        "hadErrors": false
      }
    }

2019-04-03 17:57:32.422 [ERROR] tid:23 in 'CurrentDomain_UnhandledException' C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 502
    FATAL UNHANDLED EXCEPTION: System.Management.Automation.Runspaces.InvalidPipelineStateException: Cannot invoke pipeline because it has already been invoked.
       at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
       at System.Management.Automation.Runspaces.RunspaceBase.Pulse()
       at System.Management.Automation.PSLocalEventManager.PulseEngine()
       at System.Management.Automation.PSLocalEventManager.AddAction(EventAction action, Boolean processSynchronously)
       at System.Management.Automation.PSLocalEventManager.ProcessNewEventImplementation(PSEventArgs newEvent, Boolean processSynchronously)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
I'm running the Preview extension (2.0.1) in VSCode Insiders (up-to-date as of yesterday 4/2).

**Comment by andyleejordan** [comment]
Obsolete — the old host/threading model that produced this `InvalidPipeState` is gone (3.0 rewrite). Closing.

---
_Drafted by GitHub Copilot (Claude Opus 4.8) at @andyleejordan's request._
